### ISSUE TITLE
Error Code in 13.40.14.m22 (Works without Error in 13.40.12ex)

### ISSUE THREAD

**Issue by NlGHTLORD** [muchimi/JoystickGremlinEx#116]
If someone can point me in the right direction to fix. Thanks

Uncaught exception:
Traceback (most recent call last):
   File "joystick_gremlin.py", line 2117, in _do_load_profile
   File "gremlin\base_profile.py", line 1748, in from_xml
   File "gremlin\base_profile.py", line 607, in from_xml
   File "gremlin\base_profile.py", line 2064, in from_xml
   File "gremlin\base_profile.py", line 791, in from_xml
   File "gremlin\ui\keyboard_device.py", line 95, in key
   File "gremlin\ui\keyboard_device.py", line 248, in _update
 TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
 
During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "joystick_gremlin.py", line 802, in load_profile
   File "joystick_gremlin.py", line 2284, in _load_recent_profile
   File "joystick_gremlin.py", line 2164, in _do_load_profile
   File "joystick_gremlin.py", line 813, in new_profile
   File "joystick_gremlin.py", line 2211, in _save_changes_request
   File "joystick_gremlin.py", line 2244, in _has_profile_changed
   File "gremlin\base_profile.py", line 1825, in to_xml
   File "gremlin\base_profile.py", line 1981, in get_start_mode
 IndexError: list index out of range

**Comment by muchimi** [comment]
@NlGHTLORD can you please attach your profile.  This is likely due to an old profile format not correctly handled by the newer version.  Thx.

**Comment by NlGHTLORD** [comment]
[Test.zip](https://github.com/user-attachments/files/16924064/Test.zip)

**Comment by NlGHTLORD** [comment]
Thanks!

**Comment by muchimi** [comment]
Ok thanks.  For some reason, you appear to have duplicated devices in the profile with the same name but with different GUIDs.
This is very helpul.   I'll get back to you.

**Comment by NlGHTLORD** [comment]
`	Line  9486:         <device name="Right VPC Ctrl Board" label="" device-guid="{D9BDCAA0-1814-11ED-8012-444553540000}" type="joystick">
	Line 10288:         <device name="Right VPC Ctrl Board" label="" device-guid="{E07EA130-B196-11EE-8001-444553540000}" type="joystick">
	Line 10944:         <device name="Twin USB Joystick" label="" device-guid="{E1288640-CCF4-11EE-8002-444553540000}" type="joystick">
	Line 11013:         <device name="Twin USB Joystick" label="" device-guid="{E128AD50-CCF4-11EE-8003-444553540000}" type="joystick">`

These are actually two separate button boxes. If these are the GUIDs you are referring to.

**Comment by NlGHTLORD** [comment]
I deleted these devices along with 2 others and it seems to work fine now.  I will work on my button boxes and try to find out why they share the same name.

**Comment by muchimi** [comment]
Glad you resolved it.  I added an error catch handler in the keyboard key definition in 13.40.15ex (pre-release right now) to avoid throwing an exception when it gets data that it doesn't like.  One of the enhancements I am thinking of is a profile import feature:  the general idea is to "import" a mapping from any profile into the currently selected device for the inputs that make sense as that would resolve (1) older profile data imports (2) verify profile integrity through the import process (3) allow mapping of one device from a previously saved other device.

I'll close this issue for now, noting that older profile imports and mismatched/duplicated devices need more sophistication in handling instead of just blowing up.
