### ISSUE TITLE
Error adding action conditions to TempoEx container

### ISSUE THREAD

**Issue by PainfulByte** [muchimi/JoystickGremlinEx#171]
I'm getting an list out of range error while trying to add action conditions to a TempoEx container. The whole TempoEx container disappears after the error is thrown and I cannot readd it after, I need to reload the whole profile. Using 13.40.16ex(m20)

Error in question:
`2024-11-12 09:32:10      ERROR Uncaught exception:
Traceback (most recent call last):
   File "gremlin\ui\device_tab.py", line 500, in redraw
   File "D:\Games\Tools\joystick_gremlin_13_40_16_m20\_internal\container_plugins\tempoEx\__init__.py", line 51, in __init__
    super().__init__(profile_data, parent)
   File "gremlin\ui\input_item.py", line 1636, in __init__
   File "gremlin\ui\input_item.py", line 1681, in _create_activation_condition_tab
   File "D:\Games\Tools\joystick_gremlin_13_40_16_m20\_internal\container_plugins\tempoEx\__init__.py", line 198, in _create_condition_ui
    if self.profile_data.action_sets[0] is not None:
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
 IndexError: list index out of range`

**Comment by muchimi** [comment]
Resolved in:
https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.16ex_m/joystick_gremlin_13_40_16_m21.zip

**Comment by muchimi** [comment]
Please advise if resolved.
The current patch is:
https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.16ex_m/joystick_gremlin_13_40_16_m24.zip

**Comment by PainfulByte** [comment]
Resolution confirmed.
