### ISSUE TITLE
Error when selecting Container

### ISSUE THREAD

**Issue by mnf1980** [muchimi/JoystickGremlinEx#192]
I got this error when selecting apply conditions to "Container.": m29/28/27

Uncaught exception:
Traceback (most recent call last):
   File "gremlin\ui\device_tab.py", line 640, in redraw
   File "container_plugins\basic\__init__.py", line 41, in __init__
    super().__init__(profile_data, parent)
   File "gremlin\ui\input_item.py", line 1702, in __init__
   File "gremlin\ui\input_item.py", line 1740, in _create_activation_condition_tab
   File "gremlin\ui\ui_activation_condition.py", line 56, in __init__
   File "gremlin\ui\ui_activation_condition.py", line 91, in _create_ui
 TypeError: ConditionModel.__init__() missing 1 required positional argument: 'condition_data'

**Comment by muchimi** [comment]
Thanks for reporting - was it any container or one container in particular?

**Comment by muchimi** [comment]
Looks like the basic container from the error above - I'll check it out!

**Comment by muchimi** [comment]
Resolved in m30.  The bug was introduced when the new marker for the condition tab was added.

**Comment by muchimi** [comment]
Resolved in
https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.16ex_m/joystick_gremlin_13_40_16_m30.zip

**Comment by mnf1980** [comment]
Working fine in m30. Thank you for your prompt response
