### ISSUE TITLE
Clicking the Pencil icon causes error 

### ISSUE THREAD

**Issue by mnf1980** [muchimi/JoystickGremlinEx#198]
Clicking the Pencil icon causes error.

Uncaught exception:
Traceback (most recent call last):
   File "gremlin\ui\device_tab.py", line 640, in redraw
   File "D:\joystick_gremlin_13_40_16_m29\_internal\container_plugins\button\__init__.py", line 51, in __init__
    super().__init__(profile_data, parent)
   File "gremlin\ui\input_item.py", line 1712, in __init__
   File "gremlin\ui\input_item.py", line 1615, in register
   File "gremlin\base_profile.py", line 934, in hasConditions
 TypeError: 'NoneType' object is not iterable

**Comment by muchimi** [comment]
Can you elaborate on which pencil icon is causing the issue via a screenshot?  Sorry to ask - there are lots of pencil icons in GremlinEx.

**Comment by mnf1980** [comment]
I think all the pencils in the app generate an error, so I have to close and reopen the app.

This is one of them:
![image](https://github.com/user-attachments/assets/e14f07bf-27ea-46c5-89a8-232d37796d3e)

**Comment by muchimi** [comment]
Resolved in m31.  There is still a lingering UI issue that will be resolved later in some circumstances where the container is deleted.

**Comment by muchimi** [comment]
Resolved in m31/m32:
https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.16ex_m/joystick_gremlin_13_40_16_m32.zip

**Comment by mnf1980** [comment]
resolved with M33.
