### ISSUE TITLE
Multiple errors when moving the slider in Gated Axis:

### ISSUE THREAD

**Issue by mnf1980** [muchimi/JoystickGremlinEx#219]
It is happening when I move the slider and before activating the profile:

Uncaught exception:
Traceback (most recent call last):
   File "gremlin\gated_handler.py", line 1235, in _joystick_event_handler
   File "gremlin\gated_handler.py", line 3866, in _update_slider_marker
   File "gremlin\ui\qsliderwidget.py", line 380, in setMarkerValue
   File "gremlin\ui\qsliderwidget.py", line 286, in _update_offsets
 RuntimeError: Internal C++ object (QSliderWidget) already deleted.

![image](https://github.com/user-attachments/assets/b91546ae-cdb4-4186-993e-18a2f38cd6bb)

**Comment by muchimi** [comment]
Thanks, I'll look into this QT error.

**Comment by muchimi** [comment]
Resolved in m41.

**Comment by muchimi** [comment]
Proposed solution in:
https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.16ex_m/joystick_gremlin_13_40_16_m41.zip

**Comment by muchimi** [comment]
Marking this as completed, pending any new information.
