### ISSUE TITLE
JoystickGremlinEx 13.40.7ex crashes if you start program clean with no prior run.

### ISSUE THREAD

**Issue by samkatakouzinos** [muchimi/JoystickGremlinEx#24]
JoystickGremlinEx 13.40.7ex crashes if you start program clean with no prior run.

<details>
<summary>Unhandled exception in script — text
</summary>

```
Failed to execute script 'joystick_gremlin' due to unhandled exception: [Errno 2] No such file or directory:  
'c:\\users\\samkat\\joystick gremlin\\config.json'  
  
Traceback (most recent call last):
File "joystick_gremlin.py", line 37, in <module>
File "<frozen importlib,_bootstrap>", line 1178, in _find_and_load
File "<frozen importlib,_bootstrap>", line 1149, in _find_and_load_unlocked
File "<frozen importlib,_bootstrap>", line 690, in _load_unlocked
File "Pylnstaller\loader\pyimod02_importers.py", line 352, in exec_module
File "gremlin\_init _. py", line 18, in <module>
File "<frozen importlib,_bootstrap>", line 1178, in _find_and_load
File "<frozen importlib,_bootstrap>", line 1149, in _find_and_load_unlocked
File "<frozen importlib,_bootstrap>", line 690, in _load_unlocked
File "Pylnstaller\loader\pyimod02_importers.py", line 352, in exec_module
File "gremlin\actions.py", line 24, in <module>
File "<frozen importlib,_bootstrap>", line 1178, in _find_and_load
File "<frozen importlib,_bootstrap>", line 1149, in_find_and_load_unlocked
File "<frozen importlib,_bootstrap>", line 690, in_load_unlocked
File "Pylnstaller\loader\pyimod02_importers.py", line 352, in exec_module
File "gremlin\ base_classes.py", line 27, in <module>
File "<frozen importlib,_bootstrap>", line 1178, in _find_and_load
File "<frozen importlib,_bootstrap>", line 1149, in _find_and_load_unlocked
File "<frozen importlib,_bootstrap>", line 690, in _load_unlocked
File "Pylnstaller\loader\pyimod02_importers.py", line 352, in exec_module
File "gremlin\profile.py", line 35, in <module>
File "<frozen importlib,_bootstrap>", line 1178, in _find_and_load
File "<frozen importlib,_bootstrap>", line 1149, in_find_and_load_unlocked
File "<frozen importlib,_bootstrap>", line 690, in_load_unlocked
File "Pylnstaller\loader\pyimod02_importers.py", line 352, in exec_module
File "gremlin\input_devices.py", line 359, in <module>
File "gremlin\common.py", line 34, in _call_
File "gremlin\input_devices.py", line 239, in _init
File "gremlin\ common.py", line 34, in _call
File "gremlin\config.py", line 38, in _init
File "gremlin\config.py", line 78, in reload
File "gremlin\config.py", line 83, in save
FileNotFoundError: [Errno 2] No such file or directory: 'c:\\users\\samkat\\joystick gremlin\\config.json'
```
</details>

<details>
<summary>Unhandled exception in script — image
</summary>

![240413-023827131-joystick_gremlin-1200x1348-SKG-DV-005-SKG-DV-005-samkat](https://github.com/muchimi/JoystickGremlinEx/assets/1305871/db42c6ba-98e3-4bc7-b133-f081af82cedd)

</details>

**Comment by muchimi** [comment]
Thank you.  Will look at what's going on - probably looking for a config file....

**Comment by muchimi** [comment]
Fixed in https://github.com/muchimi/JoystickGremlinEx/releases/tag/13.40.8ex

**Comment by samkatakouzinos** [comment]
Same issue again in 13.40.8ex
Does JoystickGremlinEx create the 'joystick gremlin' folder for a first run?


Traceback (most recent call last):
  File "joystick_gremlin.py", line 37, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "gremlin\__init__.py", line 18, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "gremlin\actions.py", line 24, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "gremlin\base_classes.py", line 27, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "gremlin\profile.py", line 35, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "gremlin\input_devices.py", line 359, in <module>
  File "gremlin\common.py", line 34, in __call__
  File "gremlin\input_devices.py", line 239, in __init__
  File "gremlin\common.py", line 34, in __call__
  File "gremlin\config.py", line 47, in __init__
  File "gremlin\config.py", line 97, in save
FileNotFoundError: [Errno 2] No such file or directory: 'c:\\users\\samkat\\joystick gremlin\\config.json'
